[package]
name = "tower_controller_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = {version = "1.3.20", features = ["fltk-bundled"]}
fltk-grid = "0.1.4"
clone_all = "0.1.1"